language: minimal
sudo: required

services:
  - docker

env:
  global:
    - CONDA_ENV: myrel

matrix:
  include:
  - os: osx
    python: 3.6
  - os: linux
    env: OS=centos7 PYVER=3.7

install:
  - ./install_travis.sh

script:
  - |
    if [[ $TRAVIS_OS_NAME == osx ]]; then
      ./run_travis.sh "$TRAVIS_OS_NAME"
    else
      export IMAGE=slaclcls/travis:$OS-py$PYVER
      if [[ $OS == ubuntu16.04 ]]; then
        export CC=gcc-7
        export CXX=g++-7
      else
        export CC=gcc
        export CXX=g++
      fi
      docker run -v $PWD:/build -e CONDA_ENV -e CC -e CXX -ti $IMAGE bash -l /build/run_travis.sh
    fi

notifications:
  email:
    recipients:
      - cpo@slac.stanford.edu
    on_success: change # default: change
    on_failure: always # default: always
